# Makefile
CC=g++
CFLAGS=-O2 -I ../../ -std=c++2a -ferror-limit=100 `Magick++-config --cxxflags --cppflags` `Magick++-config --ldflags --libs`

all: mnist

clean:
	rm -rf mnist

ODIR=obj

_OBJ = xor.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

mnist: 
	$(CC) -o $@ ../../artificialIntelligence/neuralNetworks/mnistNetwork.cpp $(CFLAGS)

.PHONY: clean