# Makefile
CC=g++
CFLAGS=-O2 -I ../../ -std=c++2a -ferror-limit=100 `Magick++-config --cxxflags --cppflags` `Magick++-config --ldflags --libs`

all: trainGeneralImageNetwork

clean:
	rm -rf trainGeneralImageNetwork

ODIR=obj

_OBJ = xor.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

trainGeneralImageNetwork: 
	$(CC) -o $@ ../../artificialIntelligence/neuralNetworks/trainGeneralImageNetwork.cpp $(CFLAGS)

.PHONY: clean