# Makefile
CC=g++
CFLAGS=-O2 -I ../../ -std=c++2a -ferror-limit=100

all: convNetworkMake

clean:
	rm -rf convNetworkMake

ODIR=obj

_OBJ = xor.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

convNetworkMake: 
	$(CC) -o $@ ../../artificialIntelligence/neuralNetworks/convNeuralNetwork.cpp $(CFLAGS)

.PHONY: clean