# Makefile
CC=g++
CFLAGS=-O2 -I ../../ -std=c++2a -ferror-limit=100 `Magick++-config --cxxflags --cppflags` `Magick++-config --ldflags --libs`

all: testGeneralImageNetwork

clean:
	rm -rf testGeneralImageNetwork

ODIR=obj

_OBJ = xor.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

testGeneralImageNetwork: 
	$(CC) -o $@ ../../artificialIntelligence/neuralNetworks/testGeneralImageNetwork.cpp $(CFLAGS)

.PHONY: clean