# Makefile
CC=g++
CFLAGS= -O2 -I ../../ -std=c++2a -ferror-limit=100 `wx-config --cxxflags --cppflags --libs`

all: chess

clean:
	rm -rf chess

ODIR=obj

_OBJ = xor.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

chess: 
	$(CC) -o $@ ../../chess/playChess.cpp $(CFLAGS)

.PHONY: clean