# Makefile
CC=g++
CFLAGS=-O2 -I ../../ -std=c++2a -ferror-limit=100

all: xormake

clean:
	rm -rf xormake

ODIR=obj

_OBJ = xor.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

xormake: 
	$(CC) -o $@ ../../artificialIntelligence/neuralNetworks/xor.cpp $(CFLAGS)

.PHONY: clean